server:
  port: 8080
  servlet:
    context-path: /wechat

spring:
    redis:
      host: 47.75.47.142
      port: 6379
      password: redis
  #    sentinel:
  #      master: ovft_master
  #      nodes: 192.168.2.58:26379,192.168.2.59:26379,192.168.2.60:26379
  #    password: ovfintech
